In [20]:
import tensorflow as tf
import numpy as np
import os

In [2]:
tensor_h = tf.random.normal([4,100,100,3])

In [3]:
#tensor_h[0,:,:,:]

In [4]:
#tensor_h[::2,...]

In [5]:
tensor_h[::-1].shape

TensorShape([4, 100, 100, 3])

In [6]:
tensor_h[:4].shape

TensorShape([4, 100, 100, 3])

In [7]:
tensor_h[3].shape

TensorShape([100, 100, 3])

In [8]:
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.56566644>

In [9]:
indices = [0,1,3]
tf.gather(tensor_h,axis=0,indices=indices).shape

TensorShape([3, 100, 100, 3])

In [10]:
indices = [[0,1,1,0],[1,2,2,0]]
indices[0]

[0, 1, 1, 0]

In [11]:
tf.gather_nd(tensor_h,indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.55698514, -0.4514959 ], dtype=float32)>

In [12]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("size of the original data:",expand_sample_1.shape)
print("add a dimension before the first dimension (axis = 0): " ,tf.expand_dims(expand_sample_1, axis=0).shape)
print("add a dimension before the second dimension (axis = 1): ",tf.expand_dims(expand_sample_1, axis=1).shape)
print("add a dimension before the second dimension (axis = 1): ",tf.expand_dims(expand_sample_1, axis=2).shape)
print("add a dimension after the last dimension (axis = –1): "  ,tf.expand_dims(expand_sample_1, axis=3).shape)
print("add a dimension before the second dimension (axis = 1): ",tf.expand_dims(expand_sample_1,axis=-1).shape)

size of the original data: (100, 100, 3)
add a dimension before the first dimension (axis = 0):  (1, 100, 100, 3)
add a dimension before the second dimension (axis = 1):  (100, 1, 100, 3)
add a dimension before the second dimension (axis = 1):  (100, 100, 1, 3)
add a dimension after the last dimension (axis = –1):  (100, 100, 3, 1)
add a dimension before the second dimension (axis = 1):  (100, 100, 3, 1)


In [13]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
squeeze_sample_1 = tf.random.normal([1,2,2,3])
print("size of the original data:",squeeze_sample_1.shape)

squeezed_sample_1 = tf.squeeze(squeeze_sample_1)
print("data size after dimension squeezing:",squeezed_sample_1.shape)
squeezed_sample_1 = tf.squeeze(squeezed_sample_1)
print("data size after dimension squeezing:",squeezed_sample_1.shape)

squeezed_sample_1 = tf.squeeze(squeezed_sample_1)
print("data size after dimension squeezing:",squeezed_sample_1.shape)

size of the original data: (1, 2, 2, 3)
data size after dimension squeezing: (2, 2, 3)
data size after dimension squeezing: (2, 2, 3)
data size after dimension squeezing: (2, 2, 3)


In [14]:
a = tf.constant([[ 0, 0, 0],
                 [10,10,10],
                 [20,20,20],
                 [30,30,30]])
b = tf.constant([1,2,3])

print("A: ", a    )
print("B: ", b    )
print("A,b", a + b)

A:  tf.Tensor(
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]], shape=(4, 3), dtype=int32)
B:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
A,b tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [15]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [16]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())
print("calculate the sum of all elements in the tensor (axis = None):     ",tf.reduce_sum(reduce_sample_1,axis=None).numpy())
print("calculate the sum of elements in each column by column (axis = 0): ",tf.reduce_sum(reduce_sample_1,axis=0).numpy())
print("calculate the sum of elements in each column by row (axis = 1):    ",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

original data [[1 2 3]
 [4 5 6]]
calculate the sum of all elements in the tensor (axis = None):      21
calculate the sum of elements in each column by column (axis = 0):  [5 7 9]
calculate the sum of elements in each column by row (axis = 1):     [ 6 15]


In [17]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)

#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

#Split data based on the first dimension and output the split data in a list.
result = tf.unstack(stacked_sample_1,axis=0)
print (result[0].shape)

sizes of the original data:  (100, 100, 3) (100, 100, 3)
size of the concatenated data: (2, 100, 100, 3)
(100, 100, 3)


In [18]:
split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)

splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=1)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))

splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("sizes of the split data when num_or_size_splits is set to [3,5,2]:", np.shape(splited_sample_2[0]), np.shape(splited_sample_2[1]), np.shape(splited_sample_2[2]))

size of the original data: (10, 100, 100, 3)
size of the split data when m_or_size_splits is set to 10:  (5, 10, 20, 100, 3)
sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [19]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())

sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())

sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

input tensor: [4 0 6 1 3 8 7 9 5 2]
tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
indexes of elements in ascending order: [1 3 9 4 0 8 2 6 5 7]


In [20]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())

values, index = tf.nn.top_k(sort_sample_1,5)
print("first five values in ascending order:", values.numpy())
print("indexes of the first five values in ascending order:", index.numpy())


input tensor: [1 0 9 7 2 5 4 6 8 3]
first five values in ascending order: [9 8 7 6 5]
indexes of the first five values in ascending order: [2 8 3 7 5]


In [21]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)


tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [28]:
#Graph Mode we must use with tf.Session as session, session.run()
# #Use the syntax of TensorFlow 1.x in TensorFlow 2.x. You can install the v1 compatibility package in TensorFlow 2.0 to inherit the TensorFlow 1.x code and disable the eager execution mode.
# import tensorflow.compat.v1 as tf
# tf.enable_eager_execution()

# #Create a graph and define it as a computational graph.
# x = tf.ones((2, 2), dtype=tf.dtypes.float32)
# y = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
# z = tf.matmul(x, y)
# print (z)

# #Enable the drawing function, and perform the multiplication operation to obtain data.
# with tf.Session() as sess:
#       print("z values are\n ", sess.run(z))


In [29]:
#Eager excution for conditions (control flow)
thre_1 = tf.random.uniform([], 0, 1)
x      = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)

if thre_1.numpy() > 0.5:
  y = tf.matmul(x, x)
else:
  y = tf.add(x, x)

print (y)

tf.Tensor(0.6772187, shape=(), dtype=float32)
tf.Tensor(
[[ 2  3]
 [ 6 11]], shape=(2, 2), dtype=int32)


In [30]:
#Autograph
@tf.function
def simple_nn_layer(w,x,b):
  print(b)
  return tf.nn.relu(tf.matmul(w, x)+b)

w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')

simple_nn_layer(w,x,b).shape


Tensor("b:0", shape=(), dtype=float32)


TensorShape([3, 3])

In [36]:
#Compare the perfomance in time between graph mode, and eager excution mode
#Use the timeit module to measure the execution time of a small code segment.
import timeit

image = tf.zeros([100, 200, 200, 3])

#Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))

#Use @tf.function to convert the operation into a graph.
@tf.function
def CNN_fn(image):
  return CNN_cell(image)

#Compare the execution time of the two modes.
CNN_cell(image)
cell_fun = CNN_fn(image)

#Call timeit.timeit to measure the time required for executing the code 10 times.
print("time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode:\n", 
      timeit.timeit(lambda: CNN_cell(image), number=10))

print("time required for performing the computation of one CNN layer in graph mode:\n", 
      timeit.timeit(lambda: CNN_fn(image), number=10))


time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode:
 10.741339390999201
time required for performing the computation of one CNN layer in graph mode:
 7.633622794000985


In [16]:
train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x   = np.random.random((200, 36))
val_y   = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100, validation_data=(val_x, val_y))

#Use tf.data module
dataset     = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset     = dataset.batch(32)
dataset     = dataset.repeat()

val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,validation_data=val_dataset, validation_steps=3)


Epoch 1/10
10/10 [==============================] - 0s 18ms/step - loss: 12.9495 - categorical_accuracy: 0.1040 - val_loss: 13.1429 - val_categorical_accuracy: 0.0950
Epoch 2/10
10/10 [==============================] - 0s 4ms/step - loss: 12.9444 - categorical_accuracy: 0.1020 - val_loss: 13.1405 - val_categorical_accuracy: 0.1050
Epoch 3/10
10/10 [==============================] - 0s 4ms/step - loss: 12.9427 - categorical_accuracy: 0.1020 - val_loss: 13.1400 - val_categorical_accuracy: 0.1050
Epoch 4/10
10/10 [==============================] - 0s 4ms/step - loss: 12.9417 - categorical_accuracy: 0.1020 - val_loss: 13.1395 - val_categorical_accuracy: 0.1100
Epoch 5/10
10/10 [==============================] - 0s 4ms/step - loss: 12.9418 - categorical_accuracy: 0.1030 - val_loss: 13.1409 - val_categorical_accuracy: 0.1100
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 12.9434 - categorical_accuracy: 0.1030 - val_loss: 13.1428 - val_categorical_accuracy: 0.1100
Epo

In [17]:
#Set hyperparameters.
Epochs = 10

#Define a function for dynamically setting the learning rate.
def lr_Scheduler(epoch):
  
  if epoch > 0.9 * Epochs:
    lr = 0.0001
  elif epoch > 0.5 * Epochs:
    lr = 0.001
  elif epoch > 0.25 * Epochs:
    lr = 0.01
  else:
    lr = 0.1
  
  print(lr)
  return lr


In [18]:
callbacks = [
                  #Early stopping:
                  tf.keras.callbacks.EarlyStopping(
                                                    #Metric for determining whether the model performance has no further improvement
                                                    monitor='val_loss',
                                                    #Threshold for determining whether the model performance has no further improvement
                                                    min_delta=1e-2,
                                                    #Number of epochs in which the model performance has no further improvement
                                                    patience=2),

                  #Periodically save models.
                  tf.keras.callbacks.ModelCheckpoint(
                                                      #Model path
                                                      filepath='testmodel_{epoch}.h5',
                                                      #Whether to save the optimal model.
                                                      save_best_only=True,
                                                      #Monitored metric
                                                      monitor='val_loss'),

                  #Dynamically change the learning rate.
                  tf.keras.callbacks.LearningRateScheduler(lr_Scheduler),

                  #Use TensorBoard.
                  tf.keras.callbacks.TensorBoard(log_dir='./logs')
              ]


In [19]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(10, activation='softmax'))

#Determine the optimizer (optimizer), loss function (loss), and model evaluation method (metrics).
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss  = tf.keras.losses.categorical_crossentropy, metrics=[tf.keras.metrics.categorical_accuracy])

train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x   = np.random.random((200, 36))
val_y   = np.random.random((200, 10))

history = model.fit(train_x, train_y, batch_size=16, epochs=1, callbacks=callbacks, validation_data=(val_x, val_y))


0.1
63/63 [==============================] - 1s 4ms/step - loss: 12.4715 - categorical_accuracy: 0.1080 - val_loss: 12.4679 - val_categorical_accuracy: 0.0950 - lr: 0.1000


In [29]:
# create the file
if not os.path.exists('./model/'):
  os.mkdir('./model/')

#Save models.
model_name = './model/my_saved_model.h5'
model.save(model_name)

#Import models.
new_model      = tf.keras.models.load_model(model_name)
new_prediction = new_model.predict(val_x)

#model.save_weights('./model/model_weights')
model.save_weights('./model/model_weights.h5')

#Load the weights.
#model.load_weights('./model/model_weights')
model.load_weights('./model/model_weights.h5')
